kind: pipeline
name: Build
type: docker

steps:
  - name: Restore Cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
  - name: Install Dependancies
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn install --frozen-lockfile
  - name: Build
    pull: if-not-exists
    image: node:lts-bullseye-slim
    commands:
      - yarn build
  - name: Package Files
    pull: if-not-exists
    image: node:lts-bullseye
    when:
      event: 
        - tag
      branch:
        - master
    commands:
      - zip -r build/*
      - find ./ | grep zip
  - name: Publish Release
    image: plugins/github-release
    settings:
      api_key: 
        from_secret: github_token
      files: build.zip
    when:
      event: 
        - tag
      branch:
        - master
  - name: Publish Docker
    image: plugins/docker
    pull: if-not-exists
    when:
      event: 
        - tag
      branch:
        - master
    settings:
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_password
      repo: ghcr.io/sebasptsch/jaycarsort
      registry: ghcr.io
      cache_from: ghcr.io/sebasptsch/jaycarsort
      auto_tag: true
  - name: Rebuild Cache
    image: drillster/drone-volume-cache
    pull: if-not-exists
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache
    host:
      path: /tmp/cache