/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoomIdRouteImport } from './routes/$roomId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIdIndexRouteImport } from './routes/$roomId/index'
import { Route as RoomIdManageRouteImport } from './routes/$roomId/manage'
import { Route as RoomIdAddRouteImport } from './routes/$roomId/add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdIndexRoute = RoomIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomIdRoute,
} as any)
const RoomIdManageRoute = RoomIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => RoomIdRoute,
} as any)
const RoomIdAddRoute = RoomIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => RoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRouteWithChildren
  '/login': typeof LoginRoute
  '/$roomId/add': typeof RoomIdAddRoute
  '/$roomId/manage': typeof RoomIdManageRoute
  '/$roomId/': typeof RoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$roomId/add': typeof RoomIdAddRoute
  '/$roomId/manage': typeof RoomIdManageRoute
  '/$roomId': typeof RoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRouteWithChildren
  '/login': typeof LoginRoute
  '/$roomId/add': typeof RoomIdAddRoute
  '/$roomId/manage': typeof RoomIdManageRoute
  '/$roomId/': typeof RoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$roomId'
    | '/login'
    | '/$roomId/add'
    | '/$roomId/manage'
    | '/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$roomId/add' | '/$roomId/manage' | '/$roomId'
  id:
    | '__root__'
    | '/'
    | '/$roomId'
    | '/login'
    | '/$roomId/add'
    | '/$roomId/manage'
    | '/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomIdRoute: typeof RoomIdRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId': {
      id: '/$roomId'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId/': {
      id: '/$roomId/'
      path: '/'
      fullPath: '/$roomId/'
      preLoaderRoute: typeof RoomIdIndexRouteImport
      parentRoute: typeof RoomIdRoute
    }
    '/$roomId/manage': {
      id: '/$roomId/manage'
      path: '/manage'
      fullPath: '/$roomId/manage'
      preLoaderRoute: typeof RoomIdManageRouteImport
      parentRoute: typeof RoomIdRoute
    }
    '/$roomId/add': {
      id: '/$roomId/add'
      path: '/add'
      fullPath: '/$roomId/add'
      preLoaderRoute: typeof RoomIdAddRouteImport
      parentRoute: typeof RoomIdRoute
    }
  }
}

interface RoomIdRouteChildren {
  RoomIdAddRoute: typeof RoomIdAddRoute
  RoomIdManageRoute: typeof RoomIdManageRoute
  RoomIdIndexRoute: typeof RoomIdIndexRoute
}

const RoomIdRouteChildren: RoomIdRouteChildren = {
  RoomIdAddRoute: RoomIdAddRoute,
  RoomIdManageRoute: RoomIdManageRoute,
  RoomIdIndexRoute: RoomIdIndexRoute,
}

const RoomIdRouteWithChildren =
  RoomIdRoute._addFileChildren(RoomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomIdRoute: RoomIdRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
