name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release Changeset
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      notes: ${{ steps.notes.outputs.notes }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        name: Setup Bun

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Install Dependancies
        run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun tsc -b --noEmit

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: bun changeset tag
          createGithubReleases: true
      - name: Get Release Notes
        id: notes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "notes=$(gh release view v${{ fromJson(steps.changesets.outputs.publishedPackages)[0].version }} --json body)" >> $GITHUB_OUTPUT

  publish-tauri:
    if: needs.release.outputs.published == 'true'
    name: Publish (Tauri)
    permissions:
      contents: write
    needs: release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04'
            args: '--apk'
            mobile: "android"
          - platform: 'ubuntu-22.04-arm' # Only available in public repos.
            args: ''
          - platform: 'windows-latest'
            args: ''
    runs-on: ${{ matrix.platform }}
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        name: Setup Node
        with:
          node-version: 24
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
          bun-version: latest
      - uses: actions/setup-java@v5
        name: Setup Java
        if: ${{ matrix.mobile == 'android' }}
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: "gradle"
      - name: Setup Android Signing
        if: ${{ matrix.mobile == 'android' }}
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties
        id: release-notes
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Dependancies
        run: bun install --frozen-lockfile

      - name: Install System Dependencies (Ubuntu Only)
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-22.04-arm' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Bump Cargo package version
        run: |
          cd src-tauri
          cargo install cargo-bump
          cargo-bump bump ${{ fromJson(needs.release.outputs.publishedPackages)[0].version }}
      
      - uses: tauri-apps/tauri-action@063c0231f444e55760d98acb9c469b994269d4a5
        name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_NODE_API_URL: ${{ secrets.VITE_NODE_API_URL }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'v__VERSION__'
          releaseBody: ${{ fromJson(needs.release.outputs.notes).body }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile }}